version: "3"
services:
  hub:
    image: selenium/hub:4.16
    ports:
    - 4444:4444
  chrome:
    image: selenium/node-chrome:4.16
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 0
    env_file: .env
  firefox:
    image: selenium/node-firefox:4.16
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 0
    env_file: .env
  edge:
    image: selenium/node-edge:120.0
    shm_size: "2g"
    depends_on:
    - hub
    deploy:
      replicas: 0
    env_file: .env